services:
  db:
    image: mariadb:11.8.6-ubi9
    container_name: da-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: catty_reminders
    ports:
      - "3307:3306"
    volumes:
      - /home/da/db_data:/var/lib/mysql

  app:
    image: ${IMAGE}
    container_name: da-app
    restart: unless-stopped
    ports:
      - "8181:8181"
    depends_on:
      - db

volumes:
  db_data:
    external: false
