services:
  backend:
    image: ${IMAGE}
    container_name: da-app
    restart: unless-stopped
    network_mode: host
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_USER=catty
      - DB_PASSWORD=cattypass
      - DB_NAME=catty_reminders

  db:
    image: mariadb:10.11
    container_name: da-db
    restart: unless-stopped
    network_mode: host
    environment:
      MARIADB_ROOT_PASSWORD: mypass
      MARIADB_DATABASE: catty_reminders
      MARIADB_USER: catty
      MARIADB_PASSWORD: cattypass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
