name: CD Deployment

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: course.prafdin.ru
          username: da
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 3161
          script: |
            cd /home/da/lab2_
            git fetch origin
            git reset --hard origin/lab2_
            
            COMMIT_HASH=$(git rev-parse HEAD)
            echo "Deployed commit: $COMMIT_HASH"

            echo "DEPLOY_REF=$COMMIT_HASH" > /home/da/lab2_/.env
            
            sudo systemctl restart app
